//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginTbl
    {
        public int AccountId { get; set; }

        [Required(ErrorMessage = "*Username is necessary.")]
        public string Username { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "*Password is necessary.")]
        public string Password { get; set; }
        public string AccountNo { get; set; }

        public string To_Account {get;set;}
        public Nullable<decimal> Amount { get; set; }
    }
}
