//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApproach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Father_s_Name { get; set; }
        public string Mother_s_Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
    }
}
